"""Constants and lightweight schema helpers for edit projects."""
from __future__ import annotations

from enum import Enum

SCHEMA_VERSION = 1


class FormatProfile(str, Enum):
    DESKTOP_16_9 = "DESKTOP_16_9"
    MOBILE_9_16 = "MOBILE_9_16"
    SQUARE_1_1 = "SQUARE_1_1"
    CUSTOM = "CUSTOM"


class TrackType(str, Enum):
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    GAMEPLAY = "GAMEPLAY"
    FACECAM = "FACECAM"
    CAPTIONS = "CAPTIONS"
    OVERLAY = "OVERLAY"


PUBLIC_OPERATION_TYPES = frozenset({
    "CREATE_SEQUENCE", "DELETE_SEQUENCE", "SET_SEQUENCE_FORMAT",
    "ADD_TRACK", "REMOVE_TRACK", "REORDER_TRACK",
    "ADD_CLIP", "REMOVE_CLIP", "MOVE_CLIP", "TRIM_CLIP", "SPLIT_CLIP",
    "SET_TRANSFORM", "SET_CROP", "SET_OPACITY", "SET_SPEED",
    "SET_AUDIO_GAIN", "SET_AUDIO_MUTE", "ADD_AUDIO_FADE",
    "ADD_CAPTION", "UPDATE_CAPTION", "REMOVE_CAPTION", "SET_CAPTION_STYLE",
    "SET_LAYOUT", "SET_FACECAM_VARIANT", "ADD_OVERLAY", "REMOVE_OVERLAY",
})

INTERNAL_OPERATION_TYPES = frozenset({"APPLY_STATE_PATCH", "ADD_SOURCE"})
ALL_OPERATION_TYPES = PUBLIC_OPERATION_TYPES | INTERNAL_OPERATION_TYPES

MIN_DIMENSION = 64
MAX_DIMENSION = 7680
MAX_FPS_NUMERATOR = 240000
MAX_FPS_DENOMINATOR = 1001
SNAPSHOT_INTERVAL = 25
