"""TTVturbo shared media-processing core.

Reusable foundation for audio extraction, transcription and the VOD
pipeline orchestration. No FastAPI, no React imports. The FastAPI
integration lives in :mod:`media_processing_api` at the repo root.

Design rules (see project spec):

* the pipeline module orchestrates the same services the on-demand pages
  use — it never re-implements download, audio or transcription logic;
* only ``source_type = "twitch_vod"`` is supported in this phase, but
  the source resolver is the single extension point;
* a project-wide cross-process GPU lock (see :mod:`media_processing.gpu_lock`)
  is shared between Qwen3-TTS voice-clone and faster-whisper transcription;
* all persistence is atomic JSON (tmp + os.replace) with UUID validation
  and path-traversal protection, mirroring :mod:`vod_pipeline.storage`.
"""

from __future__ import annotations

from .schemas import (
    SCHEMA_VERSION,
    SUPPORTED_SCHEMA_VERSIONS,
    ACTIVE_PIPELINE_STATUSES,
    CANCELLABLE_PIPELINE_STATUSES,
    TERMINAL_PIPELINE_STATUSES,
    AudioArtifactMetadata,
    JobType,
    MediaJob,
    MediaJobError,
    MediaJobNotFoundError,
    MediaJobConflictError,
    MediaJobValidationError,
    MediaJobStorageError,
    MediaSourceError,
    MediaSourceNotFoundError,
    MediaSourceNotReadyError,
    MediaProgress,
    PIPELINE_STEP_WEIGHTS,
    PipelineRun,
    PipelineRunError,
    PipelineRunNotFoundError,
    PipelineRunConflictError,
    PipelineRunStorageError,
    PipelineRunValidationError,
    PipelineRunUnavailableError,
    PipelineStatus,
    PipelineStep,
    PipelineStepStatus,
    PipelineStepType,
    TranscriptionMetadata,
    TranscriptionSegment,
    TranscriptionWord,
    TranscriptionStatus,
)
from .storage import MediaJobStorage
from .gpu_lock import GpuLock, GpuLockBusyError, GpuLockError, GpuLockOwner
from .sources import MediaSourceResolver, ResolvedMediaSource
from .audio_extraction import AudioExtractionService, AudioExtractionError
from .transcription import TranscriptionService, TranscriptionError
from .transcript_corrections import (
    TranscriptCorrectionError,
    TranscriptCorrectionStore,
    TranscriptRevisionConflictError,
    get_effective_segments,
    get_effective_text,
    effective_contract as transcript_effective_contract,
)
from .pipeline import PipelineService, PipelineError, DEFAULT_VOD_PIPELINE
from .conversation_mining import (
    ConversationMiningService,
    ConversationMiningError,
    ConversationMiningValidationError,
    ConversationMiningNotFoundError,
    ConversationMiningConflictError,
    ConversationMiningUnavailableError,
    MiningRunStatus,
    ACTIVE_MINING_STATUSES,
    TERMINAL_MINING_STATUSES,
    CANCELLABLE_MINING_STATUSES,
    CATEGORIES as CONVERSATION_CATEGORIES,
    SIGNALS as CONVERSATION_SIGNALS,
    MINING_CONFIG_VERSION,
    build_blocks,
    validate_model_output,
    attempt_json_repair,
    deduplicate_conversations,
    cleanup_boundaries,
    finalize_conversations,
    is_stale as mining_is_stale,
)
from .uploads import (
    UploadNotFoundError,
    UploadStorage,
    UploadStorageError,
    UploadTooLargeError,
)
from .asr_presets import (
    AsrDefaultPresetStore,
    AsrPreset,
    AsrPresetError,
    AsrPresetNotFoundError,
    BUILTIN_PRESETS,
    LEGACY_CURRENT,
    MULTILINGUAL_LARGE_V3_NO_VAD,
    MULTILINGUAL_LARGE_V3_QUALITY,
    MULTILINGUAL_LARGE_V3_TURBO,
    check_preset_compatibility,
    faster_whisper_version,
    get_preset,
    is_production_eligible,
    list_presets,
)
from .asr_metrics import (
    AsrMetricsUnavailable,
    MetricsResult,
    compute_metrics,
    hypothesis_text,
    normalise_text,
    rank_runs,
)
from .asr_benchmark import (
    AsrBenchmarkError,
    AsrBenchmarkNotFoundError,
    AsrBenchmarkService,
    recommend_winner,
)
from .audio_forensics import (
    AUDIO_VARIANTS,
    AudioForensicsService,
    DIAGNOSTICS_SUBDIR,
)
from .asr_models import (
    CANDIDATES,
    CANDIDATE_MAP,
    CanaryAdapter,
    FasterWhisperAdapter,
    ModelCandidate,
    NormalizedTranscriptionResult,
    ParakeetAdapter,
    VramTracker,
    check_candidate_available,
    check_canary_available,
    check_faster_whisper_available,
    check_parakeet_available,
    get_adapter,
    get_candidate,
    list_model_candidates,
)

__all__ = [
    "SCHEMA_VERSION",
    "SUPPORTED_SCHEMA_VERSIONS",
    "ACTIVE_PIPELINE_STATUSES",
    "CANCELLABLE_PIPELINE_STATUSES",
    "TERMINAL_PIPELINE_STATUSES",
    "AudioArtifactMetadata",
    "AudioExtractionError",
    "AudioExtractionService",
    "GpuLock",
    "GpuLockBusyError",
    "GpuLockError",
    "GpuLockOwner",
    "JobType",
    "MediaJob",
    "MediaJobConflictError",
    "MediaJobError",
    "MediaJobNotFoundError",
    "MediaJobStorageError",
    "MediaJobValidationError",
    "MediaJobStorage",
    "MediaProgress",
    "MediaSourceError",
    "MediaSourceNotFoundError",
    "MediaSourceNotReadyError",
    "MediaSourceResolver",
    "MediaSourceResolver",
    "DEFAULT_VOD_PIPELINE",
    "PIPELINE_STEP_WEIGHTS",
    "PipelineError",
    "PipelineRun",
    "PipelineRunConflictError",
    "PipelineRunError",
    "PipelineRunNotFoundError",
    "PipelineRunStorageError",
    "PipelineRunValidationError",
    "PipelineRunUnavailableError",
    "PipelineService",
    "PipelineStatus",
    "PipelineStep",
    "PipelineStepStatus",
    "PipelineStepType",
    "ResolvedMediaSource",
    "TranscriptionError",
    "TranscriptionMetadata",
    "TranscriptionSegment",
    "TranscriptionService",
    "TranscriptionStatus",
    "TranscriptionWord",
    "TranscriptCorrectionError",
    "TranscriptCorrectionStore",
    "TranscriptRevisionConflictError",
    "get_effective_segments",
    "get_effective_text",
    "transcript_effective_contract",
    "ConversationMiningService",
    "ConversationMiningError",
    "ConversationMiningValidationError",
    "ConversationMiningNotFoundError",
    "ConversationMiningConflictError",
    "ConversationMiningUnavailableError",
    "MiningRunStatus",
    "ACTIVE_MINING_STATUSES",
    "TERMINAL_MINING_STATUSES",
    "CANCELLABLE_MINING_STATUSES",
    "CONVERSATION_CATEGORIES",
    "CONVERSATION_SIGNALS",
    "MINING_CONFIG_VERSION",
    "build_blocks",
    "validate_model_output",
    "attempt_json_repair",
    "deduplicate_conversations",
    "cleanup_boundaries",
    "finalize_conversations",
    "mining_is_stale",
    "UploadNotFoundError",
    "UploadStorage",
    "UploadStorageError",
    "UploadTooLargeError",
    "AsrDefaultPresetStore",
    "AsrPreset",
    "AsrPresetError",
    "AsrPresetNotFoundError",
    "BUILTIN_PRESETS",
    "LEGACY_CURRENT",
    "MULTILINGUAL_LARGE_V3_NO_VAD",
    "MULTILINGUAL_LARGE_V3_QUALITY",
    "MULTILINGUAL_LARGE_V3_TURBO",
    "check_preset_compatibility",
    "faster_whisper_version",
    "get_preset",
    "is_production_eligible",
    "list_presets",
    "AsrMetricsUnavailable",
    "MetricsResult",
    "compute_metrics",
    "hypothesis_text",
    "normalise_text",
    "rank_runs",
    "AsrBenchmarkError",
    "AsrBenchmarkNotFoundError",
    "AsrBenchmarkService",
    "recommend_winner",
    "AUDIO_VARIANTS",
    "AudioForensicsService",
    "DIAGNOSTICS_SUBDIR",
    "CANDIDATES",
    "CANDIDATE_MAP",
    "CanaryAdapter",
    "FasterWhisperAdapter",
    "ModelCandidate",
    "NormalizedTranscriptionResult",
    "ParakeetAdapter",
    "VramTracker",
    "check_candidate_available",
    "check_canary_available",
    "check_faster_whisper_available",
    "check_parakeet_available",
    "get_adapter",
    "get_candidate",
    "list_model_candidates",
]
